apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: APPNAME-backup
  name: APPNAME-backup
  namespace: app-APPNAME
spec:
  storageClassName: APPNAME-backup
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
