apiVersion: v1
kind: PersistentVolume
metadata:
  name: APPNAME-backup
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /backup/APPNAME
  storageClassName: APPNAME-backup
