apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: cinema
  name: cinema
  namespace: app-cinema
spec:
  storageClassName: ceph-filesystem
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  volumeMode: Filesystem
