apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: studiolululala-clm
  name: studiolululala-clm-pvc
  namespace: app-studiolululala-clm
spec:
  storageClassName: studiolululala-clm
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  volumeMode: Filesystem
