apiVersion: v1
kind: PersistentVolume
metadata:
  name: studiolululala-clm
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/studiolululala-clm
  storageClassName: studiolululala-clm
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - worker
