{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.gateway.middlewares }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ join "," .Values.gateway.middlewares }}
    {{- end }}
    
    {{- if .Values.gateway.tlsEnabled }}
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- end }}

    {{- range .Values.gateway.tls }}
    {{- if .secretName }}
    traefik.ingress.kubernetes.io/router.tls.certresolver: "default"
    {{- end }}
    {{- end }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.gatewayName | default "traefik-gateway" }}
      namespace: {{ .Values.gateway.gatewayNamespace | default "traefik" }}
      sectionName: websecure
  hostnames:
    {{- range .Values.gateway.hosts }}
    - {{ .host | quote }}
    {{- end }}
  rules:
    {{- range .Values.gateway.hosts }}
    {{- $host := .host -}}
    {{- range .paths }}
    - matches:
        - path:
            type: PathPrefix
            value: {{ .path }}
      backendRefs:
        - name: {{ $.Release.Name }}
          port: {{ $.Values.service.port }}
    {{- end }}
    {{- end }}
{{- end }}