/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Syntactic Slate Design System
        'background': '#0b1326',
        'primary': '#adc6ff',
        'primary-container': '#4d8eff',
        'secondary': '#4edea3',
        'secondary-container': '#00a572',
        'tertiary': '#ffb786',
        'tertiary-container': '#df7412',
        'error': '#ffb4ab',
        'on-primary': '#002e6a',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        'on-secondary': '#003824',
        'on-tertiary': '#502400',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#c2c6d6',
        'surface': '#0b1326',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-variant': '#2d3449',
        'surface-tint': '#adc6ff',
        'outline': '#8c909f',
        'outline-variant': '#424754',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        'inverse-primary': '#005ac2',
        'secondary-fixed-dim': '#4edea3',
      },
      fontFamily: {
        headline: ['Inter', 'Noto Sans KR', 'sans-serif'],
        body: ['Inter', 'Noto Sans KR', 'sans-serif'],
        label: ['Inter', 'Noto Sans KR', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
