# ezl-app-server Helm Chart (values_prod.yaml 적용 결과 예시)

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ezl-app-server-prod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezl-app-server-prod
  labels:
    app.kubernetes.io/name: ezl-app-server
    app.kubernetes.io/instance: prod
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ezl-app-server
      app.kubernetes.io/instance: prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ezl-app-server
        app.kubernetes.io/instance: prod
    spec:
      containers:
        - name: ezl-app-server
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ezl-app-server-prod
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ezl-app-server
    app.kubernetes.io/instance: prod

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ezl-app-server-prod
spec:
  scaleTargetRef:
    name: ezl-app-server-prod
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "80"
    - type: metrics-api
      metadata:
        targetValue: "1"
        url: "https://cgojvahipd.execute-api.ap-northeast-2.amazonaws.com/default/ezlapp_helmchart_trigger"
        valueLocation: "replicas"


