apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-seungdobae
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-seungdobae
  template:
    metadata:
      labels:
        app: nginx-seungdobae
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-seungdobae
spec:
  selector:
    app: nginx-seungdobae
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-seungdobae
spec:
  ingressClassName: nginx
  rules:
  - host: nginx.seungdobae.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-seungdobae
            port:
              number: 80 